== JBoss Forge Addon for JBake
:idprefix: id_ 

This is a project to provide JBoss Forge Add-on for JBake project.

      Currently this project is in-development.

=== Dependencies: None (or)
=== Depends on
[options="header"]
|===
|Addon |Exported |Optional
|DEP1
|yes
|no
|DEP2
|yes
|yes
|===

== Setup
This Addon requires the following installation steps.
=== Add configuration to pom.xml 
To use this addon, you must add it as a dependency in the *pom.xml* of your `forge-addon` classified artifact:
(Make sure the dependency is put all the way to the left, and uses 3 spaces for indentation of GAV)
[source,xml]
----
<dependency>
   <groupId>org.jbake.forge.addon</groupId>
   <artifactId>jbake-addon</artifactId>
   <classifier>forge-addon</classifier>
   <version>${version}</version>
</dependency>
----
== Features
ABCFactory for simple ABC blah:: 
Allows for blah blah
+
[source,java]
----
@Inject private ABCFactory factory;
ABC abc = factory.createABC();
----
+
[TIP] 
====
If your addon uses a container that does not support "@Inject" annotations, services such as the `ABCFactory` may also be 
accessed via the `AddonRegistry`:
----
Imported<ABCFactory> imported = addonRegistry.getServices(ABCFactory.class);
ABCFactory factory = imported.get();
----
==== 
Creating a new XYZ instance:: 
Causes XYZ to occur
+
[source,java]
----
XYZ xyz = factory.createXYZ();
----
